

export const trans =  [
    {
      "DATE": "2025-11-01",
      "TIME": "06:08",
      "PLACE": "MEDABALMI SURYA GANESH",
      "AMOUNT": "35",
      "TYPE": "DR",
      "ACCOUNT": "HDFC  4671",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "TRAVEL",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "06:47",
      "PLACE": "A/C TRANSFER",
      "AMOUNT": "3000",
      "TYPE": "CR",
      "ACCOUNT": "IDFC  6145",
      "EXPENSE": "-",
      "INCOME": "No",
      "CATEGORY": "ACCOUNT TRANSFER",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "06:47",
      "PLACE": "NANDANA JAYACHANDARARAO",
      "AMOUNT": "3000",
      "TYPE": "DR",
      "ACCOUNT": "HDFC  4671",
      "EXPENSE": "No",
      "INCOME": "-",
      "CATEGORY": "TRANSFER",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "06:48",
      "PLACE": "ATM",
      "AMOUNT": "3000",
      "TYPE": "DR",
      "ACCOUNT": "IDFC debit 6145",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": null,
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "07:38",
      "PLACE": "ARLI SRINIVAS",
      "AMOUNT": "400",
      "TYPE": "DR",
      "ACCOUNT": "HDFC  4671",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "TRAVEL",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "11:46",
      "PLACE": "BHARATPE9O0Q7D2H9T390042@YESBANKLTD",
      "AMOUNT": "32",
      "TYPE": "DR",
      "ACCOUNT": "HDFC credit 9603",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "TRAVEL",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "14:26",
      "PLACE": "Q122391800@YBL",
      "AMOUNT": "1400",
      "TYPE": "DR",
      "ACCOUNT": "HDFC credit 9603",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "TRAVEL",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "15:02",
      "PLACE": "ORBGEN TECHNOLOGIES",
      "AMOUNT": "319.78",
      "TYPE": "DR",
      "ACCOUNT": "IDFC credit 8696",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "ENTERTAINMENT",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "15:36",
      "PLACE": "Q094966857@YBL",
      "AMOUNT": "20",
      "TYPE": "DR",
      "ACCOUNT": "HDFC credit 9603",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "TRAVEL",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-01",
      "TIME": "22:05",
      "PLACE": "PVR INOX LIMITED",
      "AMOUNT": "200",
      "TYPE": "DR",
      "ACCOUNT": "HDFC  4671",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "ENTERTAINMENT",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-02",
      "TIME": "00:05",
      "PLACE": "PVR INOX LIMITED",
      "AMOUNT": "620",
      "TYPE": "DR",
      "ACCOUNT": "HDFC credit 2788",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "ENTERTAINMENT",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-02",
      "TIME": "00:07",
      "PLACE": "PVR INOX LIMITED",
      "AMOUNT": "65",
      "TYPE": "DR",
      "ACCOUNT": "HDFC credit 2788",
      "EXPENSE": "Yes",
      "INCOME": "-",
      "CATEGORY": "ENTERTAINMENT",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-02",
      "TIME": "11:38",
      "PLACE": "JAYAHDFC@YBL",
      "AMOUNT": "20000",
      "TYPE": "CR",
      "ACCOUNT": "HSBC  4006",
      "EXPENSE": "-",
      "INCOME": "No",
      "CATEGORY": "ACCOUNT TRANSFER",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-02",
      "TIME": "11:38",
      "PLACE": "JAYACHANDARARAO N",
      "AMOUNT": "20000",
      "TYPE": "DR",
      "ACCOUNT": "HDFC  4671",
      "EXPENSE": "No",
      "INCOME": "-",
      "CATEGORY": "TRANSFER",
      "TAGS": null,
      "NOTE": null
    },
    {
      "DATE": "2025-11-02",
      "TIME": "17:20",
      "PLACE": "CREDIT",
      "AMOUNT": "15975",
      "TYPE": "CR",
      "ACCOUNT": "HSBC  XXXX",
      "EXPENSE": "-",
      "INCOME": "No",
      "CATEGORY": "INTEREST",
      "TAGS": null,
      "NOTE": null
    }
  ]

